### ISSUE TITLE
Fresh Ubuntu 16.04 doesn't work on Digital Ocean droplet

### ISSUE THREAD

**Issue by jinutm1** [superdesk/fireq#1]
Hi,

I got an ubuntu 16.04 droplet in digital ocean. I like to install live blog there, I tried the code "curl https://raw.githubusercontent.com/naspeh-sf/deploy/master/files/liveblog/install | sudo bash" as root user.

Everything was smooth on installation except the following 

![1code](https://cloud.githubusercontent.com/assets/25417255/22405073/c056e8f6-e662-11e6-941c-3878f42a3fce.PNG)
![2code](https://cloud.githubusercontent.com/assets/25417255/22405075/c32ef78a-e662-11e6-8233-b4cb4780dd15.PNG)
![3codecontinue](https://cloud.githubusercontent.com/assets/25417255/22405076/c4673bee-e662-11e6-983f-d68fb40992ba.PNG)

Please check it and give me a solution. I haven't installed anything before I run the code. I did the get-update code. It was 100 Successful.

Please help

**Comment by jinutm1** [comment]
Do i need to install any modules before the liveblog install?

**Comment by naspeh** [comment]
Hi,

Minimal requirements:
2GB RAM, 4GB Free space

Here is the session from DigitalOcean for superdesk https://github.com/superdesk/fireq/blob/master/docs/notes.md it's the same for liveblog, just replace superdesk with liveblog.

**Comment by naspeh** [comment]
I'm closing this issue, please open it again if needed yet.
