### ISSUE TITLE
After demo data installation I can't log in

### ISSUE THREAD

**Issue by CrazyEyesPete** [superdesk/fireq#20]
Does the admin login change after installing the demo data? What is a user or admin login once the demo data is installed?

**Comment by CrazyEyesPete** [comment]
Switching the database back to 'superdesk' got me logged back in, but we'd like to see the demo data so we might get some better usage ideas.

**Comment by naspeh** [comment]
```
# after 
./manage.py app:initialize_data --sample-data
# also needed user creation
python manage.py users:create -u admin -p admin -e 'admin@example.com' --admin
```
I'll update documentation soon.

Thanks.

**Comment by CrazyEyesPete** [comment]
Great! Thank you!

**Comment by naspeh** [comment]
Section is updated: https://github.com/superdesk/fireq/tree/master/files/superdesk#sample-data

I'm closing this issue.
