### ISSUE TITLE
Rethink the structure of main superdesk repo

### ISSUE THREAD

**Issue by naspeh** [superdesk/fireq#8]
We already have a bunch of un-synced branches.

## Client part
There are only changes for 
- `client/package.json` (core version changes)
- `client/superdesk.config.js`
- sometimes `po` files (like for [prod-rlne](https://github.com/superdesk/superdesk/tree/prod-rlne/client/po) branch)

In general probably it's good. There are few files been copied.

## Server part
- we have more customization in repos like [superdesk-aap](https://github.com/superdesk/superdesk-aap), [superdesk-ntb](https://github.com/superdesk/superdesk-ntb) that seems ok
- but also we have a lot of files for deployment like [server/ws.py](https://github.com/superdesk/superdesk/blob/master/server/ws.py) [server/worker.py](https://github.com/superdesk/superdesk/blob/master/server/worker.py), [server/wsgi.py](https://github.com/superdesk/superdesk/blob/master/server/wsgi.py), etc. How to synchronize changes between repos and branches I don't know

## Outdated Bamboo stuff
Just needs some cleaning.

## Extensions
`superdesk-planning` has appeared already and [it's not easy to include it](https://github.com/superdesk/superdesk/compare/planning-mvp?expand=1). Probably `liveblog` could go with `superdesk-plunning` approach, because they have a big headache in supporting core repos [PR:596 with webpack upgrade.](https://github.com/liveblog/liveblog/pull/596)

## Debugging cores and CI
It should be much easier to switch between cores and debug them, because now if use `pip install -r requirements.txt` try to find `superdesk` folder and related `apps` folder...

Now in `fireq` I use hack like this: [tpl/superdesk-dev/build-repo.sh#L13-L14](https://github.com/superdesk/fireq/blob/master/tpl/superdesk-dev/build-repo.sh#L13-L14) for easy switching without parsing `requiremets.txt` and `package.json` files and I can easy debug core related code and even could create PR from such structure...

I suggested [submodules already #2402](https://github.com/superdesk/superdesk/pull/2402) (closed this PR) with this in mind, but we still need to find a way to improve this.

## Conclusion
We need less code in such repo which been copied too often at least for server we could remove deployment and docker related stuff...

It should be easy to turn on for components like `superdesk-planing`...

After installation I assume getting structure like this:
```sh
client          # configs
client-core     # superdesk-client-core should be here
server          # configs and custom code
server-core     # superdesk-core should go here
planning        # planning if turned on
```
But again if keep in mind #7 (about configs) we need one place for configuration if it's possible...

**Comment by petrjasek** [comment]
regarding server files like wsgi etc. those could be in core, it would work the same, like it's already done for content api, so in Procfile it would be:
```
rest: gunicorn -c gunicorn_config.py superdesk.wsgi
wamp: python3 -u -m superdesk.ws
work: celery -A superdesk.worker worker
beat: celery -A superdesk.worker beat --pid=
capi: gunicorn -c gunicorn_config.py content_api.wsgi
```
and we can remove those files from server. so there would be only requirements, settings and procfile by default

**Comment by naspeh** [comment]
> only requirements, settings and procfile by default
I like this idea, It might be an option.

so `manage.py` also will go to core, after installation we'll have something like global `superdesk-manage` script or so. Right?

**Comment by naspeh** [comment]
there were few cases from yesterday proved that we have mess with main superdesk repo
- I use [branch 1.4](https://github.com/superdesk/superdesk/tree/1.4) for cores, because `master` haven't worked with previous releases, I switched to `master` to fix https://github.com/superdesk/superdesk-core/pull/859, and also switched to `master` for `superdesk-client-core`, but then reverted `1.4` for `superdesk-client-core` because `master` is not working for CI
- @jerome-poisson  fixed [superdesk.config.js](https://github.com/superdesk/superdesk/blob/wpp-1.6/client/superdesk.config.js), because it wasn't synced
- also we have this issues, when we can't install old releases, because some of dependencies have updated and brake the UI or some functionality...

**Comment by naspeh** [comment]
As I mentioned before in slack channel, I've tried to create install scripts using only cores and few as possible files, result in [files/superdesk-new/install#L123-L323][new-install]
[new-install]: https://github.com/superdesk/fireq/blob/096aefe0c47d9a1bbacb2c506d2afc9dde49353f/files/superdesk-new/install#L123-L323)
```
root@dev-sd:/opt/superdesk# tree -L 1 --dirsfirst .
.
├── client-core
├── env
├── server-core
├── activate.sh
├── manage.py
├── Procfile
└── settings.py
```
I have been mostly done for inspiration and some sort of rethinking, it's hard to have proper `settings.py` for CI jobs (because we have a bunch of different repos), but it still can be used in user/developer installations...

But still need some thinking, also keeping in mind the integration for `superdesk-planning` and `superdesk-analytics` projects, etc.

**Comment by mgogoulos** [comment]
Just found this discussion, I think that there's a mess indeed with the structure :) 

however it's very positive that you realize that and there are attempts to fix things. I'd just add my two cents, I think a structure with submodules (superdesk/superdesk being the base and all other projects as submodules) is something that could work. Also a master branch with working code is something that must be enforced. Maybe have a staging branch that PRs are merged, and then merge staging to master only when you are sure that tests pass and things are not broken? Pretty sure everybody will appreciated this

Thanks and regards
